import {
  amilllion,
  bigger,
  creative,
  harripotter,
  ourlast,
  thebookart,
  themind,
  thepast,
  therebith,
} from '../assets/images';

const Products = [
  {
    name: 'a million to one',
    image: amilllion,
    price: '50 k',
    discont: '5%',
    desc: 'Buku bagus dengan kualitas terbaik dan oke banget buat dibaca setiap hari. wajib dikoleksi ini.',
    isNew: true,
  },
  {
    name: 'the book of art',
    image: thebookart,
    price: '100 k',
    discont: '5%',
    desc: 'Buku bagus dengan kualitas terbaik dan oke banget buat dibaca setiap hari. wajib dikoleksi ini.',
    isNew: false,
  },
  {
    name: 'bigger and better',
    image: bigger,
    price: '120 k',
    discont: '5%',
    desc: 'Buku bagus dengan kualitas terbaik dan oke banget buat dibaca setiap hari. wajib dikoleksi ini.',
    isNew: true,
  },
  {
    name: 'creative ideas',
    image: creative,
    price: '60 k',
    discont: '5%',
    desc: 'Buku bagus dengan kualitas terbaik dan oke banget buat dibaca setiap hari. wajib dikoleksi ini.',
    isNew: true,
  },
  {
    name: 'Harry Potter',
    image: harripotter,
    price: '80 k',
    discont: '5%',
    desc: 'Buku bagus dengan kualitas terbaik dan oke banget buat dibaca setiap hari. wajib dikoleksi ini.',
    isNew: false,
  },
  {
    name: 'our last summer',
    image: ourlast,
    price: '150 k',
    discont: '5%',
    desc: 'Buku bagus dengan kualitas terbaik dan oke banget buat dibaca setiap hari. wajib dikoleksi ini.',
    isNew: true,
  },
  {
    name: 'the past is rising',
    image: thepast,
    price: '200 k',
    discont: '5%',
    desc: 'Buku bagus dengan kualitas terbaik dan oke banget buat dibaca setiap hari. wajib dikoleksi ini.',
    isNew: false,
  },
  {
    name: 'the rebirth of you',
    image: therebith,
    price: '250 k',
    discont: '5%',
    desc: 'Buku bagus dengan kualitas terbaik dan oke banget buat dibaca setiap hari. wajib dikoleksi ini.',
    isNew: true,
  },
  {
    name: 'think mind of leadership',
    image: themind,
    price: '90 k',
    discont: '5%',
    desc: 'Buku bagus dengan kualitas terbaik dan oke banget buat dibaca setiap hari. wajib dikoleksi ini.',
    isNew: false,
  },
];

export {Products};
